/*
 * This file is a part of the Sharemind framework.
 * Copyright (C) Cybernetica AS
 *
 * All rights are reserved. Reproduction in whole or part is prohibited
 * without the written consent of the copyright owner. The usage of this
 * code is subject to the appropriate license agreement.
 */

#ifndef SHAREMINDCOMMON_RANDOM_H
#define SHAREMINDCOMMON_RANDOM_H

#include <algorithm>
#include <cassert>
#include <cstddef>

namespace sharemind {

/**
 * This class is a header-only front-end for randomness engines.
 */
class IRandom {
public: /* Methods: */

    IRandom() { }

    virtual ~IRandom() { }

    virtual void Seed() = 0;

    virtual void Seed(const void * memptr, size_t size) = 0;

    /**
     * \brief Fills memory with randomly generated bytes.
     * \param[in] memptr pointer to memory to fill
     * \param[in] size number of bytes to fill
     */
    virtual void fillBytes(void * memptr, size_t size) = 0;

    template <typename T>
    inline void fillBlock(T * begin, T * end) {
        assert(begin <= end);
        if (begin < end) {
            fillBytes(begin, sizeof(T)*std::distance(begin, end));
        }
    }

}; /* class Random { */


} /* namespace sharemind { */

#endif /* SHAREMINDCOMMON_RANDOM_H */
